### PR TITLE
fix(oui-stepper): fix multiple calls on focus step

### PR DESCRIPTION
**Pull request by JeremyDec**
## Fix multiple calls on focus step
Backport of https://github.com/ovh-ux/ovh-ui-kit/pull/533
### Description of the Change
On focus step method is called more than once : 
- When you enter the concerned step, the method is called twice
- If the whole stepper is compiled, when you are not in the concerned step, and you go elsewhere (so the component is destroyed), the on focus method is still called

This PR fix this issues.

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report yarn-build#1684.0 ✘  
* build & test
  * build ✔ 
  * test ✘

**Comment by AxelPeter** [comment]
@JeremyDec eslint errors ;)

**Comment by ovh-cds** [comment]
CDS Report yarn-build#1686.0 ✘  
* build & test
  * build ✔ 
  * test ✘

**Comment by JeremyDec** [comment]
@AxelPeter done ;)

**Pull request merged**
